Facebook updates

diff --git a/prompt b/prompt
--- a/prompt
+++ b/prompt
@@ -1,5 +1,26 @@
 # prompt
 
-# Prints E project name, git branch name, and a frown after every failed command
-export PS1="\[\033[01;32m\]\u@\h \$(show_git_branch) \[\033[01;36m\]\w \`if [ \$? != 0 ]; then echo -e '\[\e[01;31m\]:('; fi\`\[\033[01;34m\] \$ \[\033[00m\]"
+
+# Get awesome SCM prompt support for git and hg here:
+# https://github.com/wavesoftware/scmprompt
+if [ -d scmprompt ]; then
+	source scmprompt/scmprompt.sh
+elif [ -f /opt/facebook/hg/share/scm-prompt.sh ]; then
+	source /opt/facebook/hg/share/scm-prompt.sh
+
+	PROMPT_COMMAND=__prompt_command
+
+	__prompt_command() {
+		local EXIT="$?"
+
+		# Prints E project name, git branch name, and a frown after every failed command
+		PS1="\[\033[01;32m\]\u@\h\$(_scm_prompt) \[\033[01;36m\]\w "
+
+		if [ $EXIT != 0 ]; then
+			PS1+="\[\e[01;31m\]:("
+		fi
+		PS1+="\[\033[01;34m\] \$ \[\033[00m\]"
+	}
+
+fi
 
